kojoslist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from general.views import *

admin.site.site_header = "Globalboard Admin"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]


urlpatterns += [
    url(r"^$", index, name="index"),
    # url(r"^home$", home, name="home"),
    url(r"^delete_ads$", delete_ads, name="delete_ads"),
    url(r"^delete_camp$", delete_camp, name="delete_camp"),
    url(r"^breadcrumb$", breadcrumb, name="breadcrumb"),
    url(r"^search_ads$", search_ads, name="search_ads"),
    url(r"^rate_ads$", rate_ads, name="rate_ads"),
    url(r"^update_alert$", update_alert, name="update_alert"),
    url(r"^search_camps$", search_camps, name="search_camps"),    
    url(r"^active_deactive_ads", active_deactive_ads, name="active_deactive_ads"),
    url(r"^get_post_detail$", get_post_detail, name="get_post_detail"),
    url(r"^profile", profile, name="profile"),
    url(r"^toggle_favourite", toggle_favourite, name="toggle_favourite"),
    url(r"^my-ads", my_ads, name="my-ads"),
    url(r"^explorer-campaigns", explorer_campaigns, name="explorer-campaigns"),
    url(r"^my-campaigns", my_campaigns, name="my-campaigns"),
    url(r"^my-favourites", my_favourites, name="my-favourites"),
    url(r"^my-subscriptions$", my_subscriptions, name="my-subscriptions"),
    url(r"^subscriptions/(?P<ss_id>\d*)$", edit_subscription, name="edit-subscription"),
    url(r"^post-ads/(?P<ads_id>\d*)", post_ads, name="post-ads"),
    url(r"^post-camp/(?P<camp_id>\d*)", post_camp, name="post-camp"),
    url(r"^ads/(?P<ads_id>\d*)", view_ads, name="view-ads"),
    url(r"^user_show/(?P<user_id>\d*)", user_show, name="user review"),
    url(r"^campaigns/(?P<camp_id>\d*)", view_campaign, name="view-campaign"),
    url(r"^category-ads/(?P<category_id>\d*)", category_ads, name="category-ads"),
    url(r"^category-ads-dealer/(?P<category_id>\d*)/(?P<kind>.*)", category_ads_dealer, name="category-ads-dealer"),
    url(r"^upload-image$", upload_image, name="upload-image"),
    url(r"^delete-image$", delete_image, name="delete-image"),
    url(r"^get_sub_info$", get_sub_info, name="get_sub_info"),
    url(r"^logout$", ulogout, name="logout"),
    url(r"^region-ads/st/(?P<region_id>\d+)", region_ads, {'region': 'state'}, name="state-ads"),
    url(r"^region-ads/ct/(?P<region_id>\d+)", region_ads, {'region': 'city'}, name="city-ads"),
    url(r"^region-ads/wd/(?P<region_id>\d*)", region_ads, {'region': 'world'}, name="world-ads"),
    url(r"^get_regions", get_regions, name="get_regions"),
    url(r"^verify_phone", verify_phone, name="verify_phone"),   
    url(r"^confirm-phone", confirm_phone, name="confirm-phone"),   
    url(r"^send_vcode", send_vcode, name="send_vcode"),   
    url(r"^upload_id", upload_id, name="upload_id"),   
    url(r"^about", about, name="about"),   
    url(r"^faq", faq, name="faq"),   
    url(r"^contact-us", contact_us, name="contact-us"),   
    url(r"^how-it-works", how_it_works, name="how-it-works"),   
    url(r"^why-global-board", why_global_board, name="why-global-board"),   
    url(r"^terms-of-use", terms_of_use, name="terms-of-use"), 
    url(r"^why-use", why_use, name="why-use"),     
    url(r"^customer-support", customer_support, name="customer-support"),           
    url(r"^my-account", my_account, name="my-account"),   
    url(r"^send_friend_email", send_friend_email, name="send_friend_email"), 
    url(r"^send_reply_email", send_reply_email, name="send_reply_email"),        
    url(r"^create-subscription", create_subscription, name="create-subscription"),        
    url(r"^remove-subscription", remove_subscription, name="remove-subscription"), 
    url(r"^release_purchase", release_purchase, name="release_purchase")
]

general/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

VSTATUS = (
    ('unverified', 'Unverified'),
    ('awaiting_approve', 'Awaiting Approve'),
    ('approved', 'Approved')
)

class Customer(AbstractUser):
    avatar = models.CharField(max_length=100, default="default_avatar.png")
    phone = models.CharField(max_length=20, blank=True, null=True)
    phone_verified = models.BooleanField(default=False)
    dob = models.CharField(max_length=50, blank=True, null=True)
    forum_handle = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    # cache location
    default_site = models.CharField(max_length=100, blank=True, null=True)
    duration = models.CharField(max_length=100, blank=True, null=True)
    v_statue = models.CharField(max_length=50, choices=VSTATUS, default='unverified')
    id_photo = models.ImageField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.username


class Category(models.Model):
    parent = models.ForeignKey("Category", blank=True, null=True)
    name = models.CharField(max_length=50)
    column = models.IntegerField(default=1) # 10: dealer for sub category
    form = models.CharField(max_length=50, default='Post')
    price = models.FloatField(default=0)
    order = models.IntegerField(default=1) # for display

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ads Category'
        verbose_name_plural = 'Ads Categories'
        ordering = ['name']


class Country(models.Model):
    sortname = models.CharField(max_length=3)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Countries'


class State(models.Model):
    name = models.CharField(max_length=150)
    country = models.ForeignKey(Country)

    def __str__(self):
        return self.name.encode('utf-8')


class City(models.Model):
    """
    cities do not have district
    districts have district as parent city
    """
    name = models.CharField(max_length=30)
    state = models.ForeignKey(State)
    district = models.ForeignKey("City", blank=True, null=True, related_name='districts')

    def __str__(self):
        return self.name.encode('utf-8')

    class Meta:
        verbose_name_plural = 'Cities'


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    status = models.CharField(max_length=50, blank=True, null=True)
    category = models.ForeignKey(Category)
    price = models.FloatField(default=0, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(Customer)
    region = models.ForeignKey(City, blank=True, null=True)
    language = models.CharField(max_length=50, blank=True, null=True)
    # contact
    mail_relay = models.BooleanField(default=False)
    real_email = models.BooleanField(default=False)
    no_reply = models.BooleanField(default=False)
    by_phone = models.BooleanField(default=False)
    by_text = models.BooleanField(default=False)
    phone = models.CharField(max_length=20, blank=True, null=True)
    extension = models.CharField(max_length=10, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    allow_other_contact = models.BooleanField(default=False)
    by_dealer = models.BooleanField(default=False)

    def __str__(self):
        return self.title


PURCHASE_TYPE = (
    ('direct', 'DIRECT'),
    ('escrow', 'ESCROW')
)

PURCHASE_STATUS = (
    (0, 'FINISHED SUCCESSFULLY'),
    (1, 'WAIT RELEASE'),
    (2, 'UNDER DISPUTE')
)

class PostPurchase(models.Model):
    post = models.ForeignKey(Post)
    purchaser = models.ForeignKey(Customer)
    type = models.CharField(max_length=20, choices=PURCHASE_TYPE)
    contact = models.TextField(blank=True, null=True)
    transaction = models.CharField(max_length=100)
    status = models.IntegerField(choices=PURCHASE_STATUS, default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.post.title, self.purchaser.username)


class Review(models.Model):
    """
    review on post
    """
    post = models.ForeignKey(Post)
    rater = models.ForeignKey(Customer)
    rating = models.FloatField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.post.title, self.rater.username)


class Search(models.Model):
    keyword = models.CharField(max_length=100, blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, null=True)
    city = models.ForeignKey(City, blank=True, null=True)
    state = models.ForeignKey(State, blank=True, null=True)
    owner = models.ForeignKey(Customer)
    created_at = models.DateTimeField(auto_now_add=True)
    alert = models.BooleanField(default=True)
    search_title = models.BooleanField(default=False)
    has_image = models.BooleanField(default=False)
    min_price = models.FloatField(blank=True, null=True)
    max_price = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.owner.username

    class Meta:
        verbose_name = 'Subscription'
        verbose_name_plural = 'Subscriptions'


class Image(models.Model):
    post = models.ForeignKey(Post, related_name='images')
    name = models.CharField(max_length=100)

    def __str__(self):
        return '{} - {}'.format(self.post.title, self.name)



class Favourite(models.Model):
    owner =  models.ForeignKey(Customer, related_name="favourites")
    post = models.ForeignKey(Post)

    def __str__(self):
        return '{} - {}'.format(self.owner.first_name, self.post.title)


class Hidden(models.Model):
    owner =  models.ForeignKey(Customer)
    post = models.ForeignKey(Post, related_name='post')

    def __str__(self):
        return '{} - {}'.format(self.owner.first_name, self.post.title)


class Perk(models.Model):
    title = models.CharField(max_length=200)
    campaign = models.ForeignKey("Campaign")
    price = models.IntegerField()
    retail = models.IntegerField(default=0)
    description = models.TextField()
    num_avail = models.IntegerField(default=1000000)
    num_claimed = models.IntegerField(default=0)
    image = models.ImageField(upload_to="perks", blank=True, null=True)

    def __str__(self):
        return '{} - {}'.format(self.campaign.title, self.title)


class PerkClaim(models.Model):
    campaign = models.ForeignKey("Campaign", related_name="claims")
    # null for donate
    perk = models.ForeignKey(Perk, blank=True, null=True, related_name="claims")
    contact = models.TextField(blank=True, null=True)
    # null for Anonymous
    claimer = models.ForeignKey(Customer, blank=True, null=True)
    amount = models.IntegerField()      # in cent
    transaction = models.CharField(max_length=100)

    def __str__(self):
        return self.campaign.title


class CampCategory(models.Model):
    parent = models.ForeignKey("CampCategory", blank=True, null=True)
    name = models.CharField(max_length=50)
    column = models.IntegerField(default=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Campaign Category'
        verbose_name_plural = 'Campaign Categories'


STAGES = [
    ('concept', 'CONCEPT'),
    ('prototype', 'PROTOTYPE'),
    ('production', 'PRODUCTION'),
    ('shipping', 'SHIPPING')
]

class Campaign(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(CampCategory)
    budget = models.IntegerField()
    raised = models.IntegerField(default=0)
    over_image = models.CharField(max_length=200)
    overview = models.TextField()
    content = models.TextField()
    stage = models.CharField(max_length=200, choices=STAGES)
    duration = models.IntegerField()
    tagline = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    # youtube video keys
    videos = models.TextField(blank=True, null=True)
    owner =  models.ForeignKey(Customer)
    created_at = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.title

templates/_base.html
<!DOCTYPE html>
<html lang="en-GB">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <title>Global Board &#8211; View ads from all over the World</title>
    <link rel='dns-prefetch' href='//fonts.googleapis.com' />
    <link rel='dns-prefetch' href='//s.w.org' />

    <link rel='stylesheet' id='contact-form-7-css' href='/static/plugins/contact-form-7/includes/css/styles.css' type='text/css' media='all' />
    <link rel='stylesheet' id='userpro_google_font-css' href='/static/css/google-font-1.css' type='text/css' media='all' />
    <link rel='stylesheet' id='userpro_min-css' href='/static/plugins/userpro/css/userpro.min.css' type='text/css' media='all' />
<!--     <link rel='stylesheet' id='userpro_lightview-css' href='/static/plugins/userpro/css/lightview/lightview.css' type='text/css' media='all' />
    <link rel='stylesheet' id='userpro_jquery_ui_style-css' href='/static/plugins/userpro/css/userpro-jquery-ui.css' type='text/css' media='all' />
    <link rel='stylesheet' id='userpro_skin_min-css' href='/static/plugins/userpro/skins/elegant/style.css' type='text/css' media='all' />
 -->    <link rel='stylesheet' id='bootstrap-css' href='/static/css/bootstrap-3.3.6-dist/css/bootstrap.min.css' type='text/css' media='all' />
    <link rel='stylesheet' id='font-awesome-css' href='/static/css/font-awesome-4.7.0/css/font-awesome.min.css' type='text/css' media='all' />
    <link rel='stylesheet' id='globoard-fonts-css' href='/static/css/fonts/font.css' type='text/css' media='all' />
    <link rel='stylesheet' id='select-2-css' href='/static/css/select2.min.css' type='text/css' media='all' />
    <link rel='stylesheet' id='ammap-css' href='/static/css/ammap.css' type='text/css' media='all' />
    <link rel='stylesheet' id='style-css' href='/static/css/style.css?262' type='text/css' media='all' />
    <link rel='stylesheet' href='/static/css/extra.css?12' type='text/css' />

    <script type='text/javascript' src='/static/js/jquery/jquery.js'></script>
    <script type='text/javascript' src='/static/js/jquery.min.js'></script>
    <script type='text/javascript' src='/static/js/jquery/jquery-migrate.min.js'></script>
    <!--[if lt IE 9]>
<script type='text/javascript' src='/static/js/html5.js'></script>
<![endif]-->
    <script type='text/javascript' src='/static/css/bootstrap-3.3.6-dist/js/bootstrap.min.js'></script>
    <script type='text/javascript' src='/static/js/select2.min.js'></script>
    <script type='text/javascript' src='/static/js/ammap.js'></script>
    <script type='text/javascript' src='/static/js/worldLow.js'></script>
    <script type='text/javascript' src='/static/js/black.js'></script>
    <script type='text/javascript' src='/static/js/main_map.js'></script>
    <script type='text/javascript' src='/static/js/customscript.js?v=5'></script>
    <script type='text/javascript' src="/static/js/jquery-ui.js"></script>
    <!-- <script type='text/javascript' src='/static/plugins/userpro/addons/social/scripts/userpro-social.min.js'></script> -->

    {% block extra_css %} 
    {% endblock %}

</head>

<body class="home page-template page-template-page-home page-template-page-home-php page page-id-4 wp-custom-logo">
    {% block page_content %} 
    {% endblock %}

    <script type='text/javascript' src='/static/plugins/contact-form-7/includes/js/jquery.form.min.js'></script>
    <script type='text/javascript' src='/static/plugins/contact-form-7/includes/js/scripts.js'></script>
    <script type='text/javascript' src='/static/js/jquery/ui/core.min.js'></script>
<!--     <script type='text/javascript' src='/static/plugins/userpro/scripts/swfobject.js'></script>
    <script type='text/javascript' src='/static/plugins/userpro/scripts/spinners/spinners.min.js'></script>
    <script type='text/javascript' src='/static/plugins/userpro/scripts/lightview/lightview.js'></script>
    <script type='text/javascript' src='/static/plugins/userpro/scripts/scripts.js'></script>
    <script type='text/javascript' src='/static/plugins/userpro/scripts/performance.js'></script>
 -->
    {% block extra_js %} 
    {% endblock %}
</body>

</html>

templates/_category.html
{% for mmc in categories %}
    <div class="col-md-24 col-xs-11">
        {% for mc in mmc %}
            <div class="category row{{forloop.counter}} {% if mc.0.form == '10' %} hidden-xs {% elif mc.0.form == '20' %} visible-xs {% endif %}">
                <a href="javascript:void();" data-toggle="collapse" data-target="#c{{mc.0.id}}">{{ mc.0.name }}</a>
            </div>
            <div class="sub-category row{{forloop.counter}} {% if mc.0.form == '10' %} hidden-xs {% elif mc.0.form == '20' %} visible-xs {% endif %} collapse" id="c{{mc.0.id}}">
            {% for cc in mc.1 %}
                {% if cc.category_set.all %}
                    <a href="javascript:void();" data-toggle="collapse" data-target="#c{{cc.id}}">{{ cc.name }}</a>
                    <div id="c{{cc.id}}" class="collapse">
                    {% for ccc in cc.category_set.all %}
                        <a href="/category-ads/{{ ccc.id }}">&nbsp;&nbsp;&nbsp;&nbsp;{{ ccc.name }}</a>
                    {% endfor %}
                    </div>
                {% else %}
                    {% if cc.column == 20 %}
                        <a href="{{ cc.form }}">{{ cc.name }}</a>
                    {% else %}
                        <a href="/category-ads/{{ cc.id }}">{{ cc.name }}</a>
                    {% endif %}
                {% endif %}
            {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endfor %}

templates/_city_list.html
<ul class='country-list'>
{% if cities %}
    {% for city in cities %}
		<li>
			<a href="javascript:void();" class="city_id" data-id="{{ city.id }}">{{ city.name }}</a>
		</li>
    {% endfor %}
{% else %}
	No city found   
{% endif %}
</ul>

templates/_state_list.html
<ul class='country-list'>
    {% for state in states %}
		<li data-id="{{ state.name }}" class="region_id"><a href="javascript:void();">{{ state.name }}</a></li>
    {% endfor %}
</ul>

templates/ads-list.html
{% extends "profile.html" %} 
{% load staticfiles %} 


{% block right_content %}
    <!-- Content Right Content -->

    <div class="col-sm-12 full-h">

        <div class="content-right-content my-ads row">
            <nav class="breadcrumb">                                        
            {% autoescape off %}{{ breadcrumb }}{% endautoescape %}
            </nav>

            <h2>
                Ads List 
                {% if category %}
                    <small> (
                    {% if category.parent.parent %}
                        {{ category.parent.parent.name }} / 
                    {% elif category.parent %}
                        {{ category.parent.name }} / 
                    {% endif %}
                    {{ category.name }}
                    )</small>
                {% endif %}
            </h2>            
            <form method="post" class="search-form">
            {% csrf_token %}
            <input type="hidden" name="others" value="true">
            <div class="{% if no_subscription %} col-md-10 {% else %} col-md-8 {% endif %} ads_search search">
                <input type="text" class="search-input ads_search_input" name="keyword" placeholder="Search for ads name...">
            </div>
            <div class="col-md-2 ads_search">
                <input type="button" id="search_ads" class="btn btn-info" value="Search">
            </div>
            {% if not no_subscription %}
                <div class="col-md-2 ads_search">
                    <input type="button" class="btn btn-info subscribe" value="Subscribe" style="line-height: 17px;">
                </div>
            {% endif %}
            <div class="col-md-12 m-t-15">
                <a class="" href="javascript: void();" onclick="$('.filters').toggle();"><i class="fa fa-filter"></i> More filters</a>
                <select class="view-mode" name="view_mode">
                    <option value="_post_list.html">List View</option>
                    <option value="_gads_list.html">Gallery</option>
                </select>
            </div>
            <div class="col-md-12 m-t-15 filters well" style="display: none;">
                <div class="row" style="margin-bottom: 12px;">
                <div class="col-md-2">
                    <div class="checkbox">
                        <label><input type="checkbox" id="ck_search_title" style="margin-top: 0;" value="true" name="ck_search_title">Search titles only</label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        <label><input type="checkbox" id="ck_has_image" style="margin-top: 0;" value="true" name="ck_has_image"> Has image</label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="checkbox">
                        <label><input type="checkbox" id="ck_posted_today" name="ck_posted_today" style="margin-top: 0;" value="true"> Posted today</label>
                    </div>
                </div>
                <div class="col-md-6 form-inline">
                    <div class="form-group">
                        <label for="email" style="margin-right:12px;">Price: </label>
                        <input type="number" min="0" name="price__gte" id="price__gte" class="form-control" placeholder="Min price">
                        <input type="number" min="0" name="price__lte" id="price__lte" class="form-control" placeholder="Max price">
                    </div>
                </div>
                </div>
                <input type="hidden" name="model" value="{{ category.form }}">
                {% if category %}
                    {% include 'search/'|add:category.form|add:'.html' %}
                {% endif %}
            </div>
            </form>
            <div class="ads_list" id="ads_list">
            {% include '_post_list.html' %}            
            </div>
        </div>

    </div>
{% endblock %}

{% block load_highcharts_js %}
{% endblock %}

{% block own_js %}
<script src="https://checkout.stripe.com/checkout.js"></script>

<script type="text/javascript">
    var price = 200; 

    var handler = StripeCheckout.configure({
        key: '{{ skey }}',
        locale: 'auto',
        token: function(token) {
            save_subscription(token.id);
        }
    });

    function save_subscription(token) {
        jQuery.ajax({
            type: 'post',
            url: '/create-subscription',
            data: {
                keyword: jQuery('.ads_search_input').val(),
                search_title: $('#ck_search_title').prop('checked'),
                has_image: $('#ck_has_image').prop('checked'),
                min_price: $('#price__gte').val(),
                max_price: $('#price__lte').val(),
                stripeToken: token
            },
            success: function (data) {
                alert('Subscribed successfully!');
            }
        }); 
    }

    $('.subscribe').on('click', function(e) {
        var keyword = jQuery('.ads_search_input').val();

        if (!logged_in) {
            var r = confirm("You need to login for subscription!");
            if (r == true) {
                location.href = "/accounts/login/?next="+url;
            }
            return;
        }

        // if (keyword.trim() == '') {
        //     alert('Please specify the keyword!');
        //     $('.ads_search_input').focus();
        //     return;
        // }
        // save_subscription('');

        handler.open({
            name: "Globalboard",
            description: "Create a new subscription",
            currency: "usd",
            amount: price
        });
    });    
</script>

<script>
    var logged_in = {% if user.is_authenticated %} true {% else %} false {% endif %};
    var url = "{{ request.path }}";

    jQuery(document).ready(function(){                
        jQuery('#search_ads').click(function() {
            search_ads();
        });

        jQuery('.ads_search_input').keypress(function(e) {
            var key = e.which;
            if (key == 13) {
                search_ads();
            }
        });

        $('.view-mode').change(function() {
            search_ads();
        });

        $('#ck_search_title').click(function() {
            search_ads();
        });

        $('#ck_has_image').click(function() {
            search_ads();
        });

        $('#ck_posted_today').click(function() {
            search_ads();
        });

        function search_ads() {
            var min_val = +$('#price__gte').val(),
                max_val = +$('#price__lte').val();

            if ($('#price__lte').val() && min_val > max_val) {
                alert('Filter for price is wrong.');
                $('#price__gte').val('');
                $('#price__lte').val('');
                $('#price__gte').focus();
            }

            jQuery.ajax({
                type: 'post',
                url: '/search_ads',
                data: $('.search-form').serialize(),
                success: function (data) {
                    jQuery('#ads_list').html(data);
                }
            });                     
        }
    });  

    $("body").on('click', 'a.breadcrumb-item', function() {
        location.href = '/profile#' + $(this).data('mapname');
    });

    $('.cl_datepicker').datetimepicker({
        format: 'YYYY-MM-DD'
    });

    $('.cl_timepicker').datetimepicker({
        format: 'H:m'
    });        

</script>

{% endblock %}

templates/choose_dealer_class.html
{% extends "profile.html" %} 
{% load staticfiles %} 

{% block right_content %}
    <!-- Content Right Content -->

    <div class="col-sm-12 full-h">

        <div class="content-right-content my-ads choose-dealer row">
            <h3>{{ category.name }}</h3>
            <div class="col-md-12">
                <a href="/category-ads-dealer/{{ category.id }}/all">
                    All Ads 
                </a><div>(dealer + by-owner)</div>
                <a href="/category-ads-dealer/{{ category.id }}/owner">
                    By Owner Only 
                </a><div>(private party, no dealers)</div>
                <a href="/category-ads-dealer/{{ category.id }}/dealer">
                    By Dealer Only 
                </a><div>(no private party)</div>
            </div>
        </div>

    </div>
{% endblock %}

{% block load_highcharts_js %}
{% endblock %}

{% block own_js %}
{% endblock %}

templates/why-use.html
{% extends "index.html" %} 
{% load staticfiles %} 

{% block extra_css %} 
    <link rel='stylesheet' href='/static/css/with-map.css' type='text/css' />
{% endblock %}


{% block page_body %}
<div class="title_page">Why Use</div>
<div class="col-xs-12">
	<div class="content"><p>We monitor requests and postings of goods and services and send alerts to save you time.  Sign up to receive notifications, and we will do the rest. The user can get direct access to real on demand Ads for good and services.</p>
	</div>
</div>
{% endblock %}

templates/wraper.html
<!DOCTYPE html>
<html lang="en-GB">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <title>Global Board &#8211; View ads from all over the World</title>
    <link rel='stylesheet' href='/static/css/extra.css' type='text/css' />
    <link rel='stylesheet' id='font-awesome-css' href='/static/css/font-awesome-4.7.0/css/font-awesome.min.css' type='text/css' media='all' />
    <link rel='stylesheet' id='bootstrap-css' href='/static/css/bootstrap-3.3.6-dist/css/bootstrap.min.css' type='text/css' media='all' />
</head>
<body style="overflow: hidden; width: 100%; height: 100%;">
    <iframe style="position: absolute;height: 100%;width: 100%;border: none;left: 0;top: 0;" allowfullscreen src="{{ next }}"></iframe>
    {% if user.is_authenticated and not logout %}
    <div class="chat-wrapper">
        <div class="chat-header">
            <div class="chat-title"><i class="fa fa-comments"></i> Chat</div>
            <div class="chat-close"><i class="fa fa-window-maximize"></i><i class="fa fa-window-minimize hidden"></i></div>
        </div>
        <div class="chat-body">
            <iframe class="chat-frame" src="/static/chat/index.html?uid={{ user.email }}"></iframe>
        </div>
    </div>  

    <script type='text/javascript' src='/static/js/jquery.min.js'></script>
    <script type="text/javascript">
        $('.chat-header').on('click', function() {
            $('.fa-window-maximize').toggleClass('hidden');
            $('.fa-window-minimize').toggleClass('hidden');
            $('.chat-wrapper').toggleClass('show-chat');
        });
    </script>
    {% endif %}

</body>
</html>