kojoslist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from general.views import *

admin.site.site_header = "Globalboard Admin"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]


urlpatterns += [
    url(r"^$", index, name="index"),
    # url(r"^home$", home, name="home"),
    url(r"^delete_ads$", delete_ads, name="delete_ads"),
    url(r"^delete_camp$", delete_camp, name="delete_camp"),
    url(r"^breadcrumb$", breadcrumb, name="breadcrumb"),
    url(r"^search_ads$", search_ads, name="search_ads"),
    url(r"^rate_ads$", rate_ads, name="rate_ads"),
    url(r"^update_alert$", update_alert, name="update_alert"),
    url(r"^search_camps$", search_camps, name="search_camps"),    
    url(r"^active_deactive_ads", active_deactive_ads, name="active_deactive_ads"),
    url(r"^get_post_detail$", get_post_detail, name="get_post_detail"),
    url(r"^profile", profile, name="profile"),
    url(r"^toggle_favourite", toggle_favourite, name="toggle_favourite"),
    url(r"^my-ads", my_ads, name="my-ads"),
    url(r"^explorer-campaigns", explorer_campaigns, name="explorer-campaigns"),
    url(r"^my-campaigns", my_campaigns, name="my-campaigns"),
    url(r"^my-favourites", my_favourites, name="my-favourites"),
    url(r"^my-subscriptions$", my_subscriptions, name="my-subscriptions"),
    url(r"^subscriptions/(?P<ss_id>\d*)$", edit_subscription, name="edit-subscription"),
    url(r"^post-ads/(?P<ads_id>\d*)", post_ads, name="post-ads"),
    url(r"^post-camp/(?P<camp_id>\d*)", post_camp, name="post-camp"),
    url(r"^ads/(?P<ads_id>\d*)", view_ads, name="view-ads"),
    url(r"^user_show/(?P<user_id>\d*)", user_show, name="user review"),
    url(r"^campaigns/(?P<camp_id>\d*)", view_campaign, name="view-campaign"),
    url(r"^category-ads/(?P<category_id>\d*)", category_ads, name="category-ads"),
    url(r"^category-ads-dealer/(?P<category_id>\d*)/(?P<kind>.*)", category_ads_dealer, name="category-ads-dealer"),
    url(r"^upload-image$", upload_image, name="upload-image"),
    url(r"^delete-image$", delete_image, name="delete-image"),
    url(r"^get_sub_info$", get_sub_info, name="get_sub_info"),
    url(r"^logout$", ulogout, name="logout"),
    url(r"^region-ads/st/(?P<region_id>\d+)", region_ads, {'region': 'state'}, name="state-ads"),
    url(r"^region-ads/ct/(?P<region_id>\d+)", region_ads, {'region': 'city'}, name="city-ads"),
    url(r"^region-ads/wd/(?P<region_id>\d*)", region_ads, {'region': 'world'}, name="world-ads"),
    url(r"^get_regions", get_regions, name="get_regions"),
    url(r"^verify_phone", verify_phone, name="verify_phone"),   
    url(r"^confirm-phone", confirm_phone, name="confirm-phone"),   
    url(r"^send_vcode", send_vcode, name="send_vcode"),   
    url(r"^upload_id", upload_id, name="upload_id"),   
    url(r"^about", about, name="about"),   
    url(r"^faq", faq, name="faq"),   
    url(r"^contact-us", contact_us, name="contact-us"),   
    url(r"^how-it-works", how_it_works, name="how-it-works"),   
    url(r"^why-global-board", why_global_board, name="why-global-board"),   
    url(r"^terms-of-use", terms_of_use, name="terms-of-use"), 
    url(r"^why-use", why_use, name="why-use"),     
    url(r"^customer-support", customer_support, name="customer-support"),           
    url(r"^my-account", my_account, name="my-account"),   
    url(r"^send_friend_email", send_friend_email, name="send_friend_email"), 
    url(r"^send_reply_email", send_reply_email, name="send_reply_email"),        
    url(r"^create-subscription", create_subscription, name="create-subscription"),        
    url(r"^remove-subscription", remove_subscription, name="remove-subscription"), 
    url(r"^release_purchase", release_purchase, name="release_purchase")
]

general/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

VSTATUS = (
    ('unverified', 'Unverified'),
    ('awaiting_approve', 'Awaiting Approve'),
    ('approved', 'Approved')
)

class Customer(AbstractUser):
    avatar = models.CharField(max_length=100, default="default_avatar.png")
    phone = models.CharField(max_length=20, blank=True, null=True)
    phone_verified = models.BooleanField(default=False)
    dob = models.CharField(max_length=50, blank=True, null=True)
    forum_handle = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    # cache location
    default_site = models.CharField(max_length=100, blank=True, null=True)
    duration = models.CharField(max_length=100, blank=True, null=True)
    v_statue = models.CharField(max_length=50, choices=VSTATUS, default='unverified')
    id_photo = models.ImageField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.username


class Category(models.Model):
    parent = models.ForeignKey("Category", blank=True, null=True)
    name = models.CharField(max_length=50)
    column = models.IntegerField(default=1) # 10: dealer for sub category
    form = models.CharField(max_length=50, default='Post')
    price = models.FloatField(default=0)
    order = models.IntegerField(default=1) # for display

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ads Category'
        verbose_name_plural = 'Ads Categories'
        ordering = ['name']


class Country(models.Model):
    sortname = models.CharField(max_length=3)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Countries'


class State(models.Model):
    name = models.CharField(max_length=150)
    country = models.ForeignKey(Country)

    def __str__(self):
        return self.name.encode('utf-8')


class City(models.Model):
    """
    cities do not have district
    districts have district as parent city
    """
    name = models.CharField(max_length=30)
    state = models.ForeignKey(State)
    district = models.ForeignKey("City", blank=True, null=True, related_name='districts')

    def __str__(self):
        return self.name.encode('utf-8')

    class Meta:
        verbose_name_plural = 'Cities'


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    status = models.CharField(max_length=50, blank=True, null=True)
    category = models.ForeignKey(Category)
    price = models.FloatField(default=0, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(Customer)
    region = models.ForeignKey(City, blank=True, null=True)
    language = models.CharField(max_length=50, blank=True, null=True)
    # contact
    mail_relay = models.BooleanField(default=False)
    real_email = models.BooleanField(default=False)
    no_reply = models.BooleanField(default=False)
    by_phone = models.BooleanField(default=False)
    by_text = models.BooleanField(default=False)
    phone = models.CharField(max_length=20, blank=True, null=True)
    extension = models.CharField(max_length=10, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    allow_other_contact = models.BooleanField(default=False)
    by_dealer = models.BooleanField(default=False)

    def __str__(self):
        return self.title


PURCHASE_TYPE = (
    ('direct', 'DIRECT'),
    ('escrow', 'ESCROW')
)

PURCHASE_STATUS = (
    (0, 'FINISHED SUCCESSFULLY'),
    (1, 'WAIT RELEASE'),
    (2, 'UNDER DISPUTE')
)

class PostPurchase(models.Model):
    post = models.ForeignKey(Post)
    purchaser = models.ForeignKey(Customer)
    type = models.CharField(max_length=20, choices=PURCHASE_TYPE)
    contact = models.TextField(blank=True, null=True)
    transaction = models.CharField(max_length=100)
    status = models.IntegerField(choices=PURCHASE_STATUS, default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.post.title, self.purchaser.username)


class Review(models.Model):
    """
    review on post
    """
    post = models.ForeignKey(Post)
    rater = models.ForeignKey(Customer)
    rating = models.FloatField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.post.title, self.rater.username)


class Search(models.Model):
    keyword = models.CharField(max_length=100, blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, null=True)
    city = models.ForeignKey(City, blank=True, null=True)
    state = models.ForeignKey(State, blank=True, null=True)
    owner = models.ForeignKey(Customer)
    created_at = models.DateTimeField(auto_now_add=True)
    alert = models.BooleanField(default=True)
    search_title = models.BooleanField(default=False)
    has_image = models.BooleanField(default=False)
    min_price = models.FloatField(blank=True, null=True)
    max_price = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.owner.username

    class Meta:
        verbose_name = 'Subscription'
        verbose_name_plural = 'Subscriptions'


class Image(models.Model):
    post = models.ForeignKey(Post, related_name='images')
    name = models.CharField(max_length=100)

    def __str__(self):
        return '{} - {}'.format(self.post.title, self.name)



class Favourite(models.Model):
    owner =  models.ForeignKey(Customer, related_name="favourites")
    post = models.ForeignKey(Post)

    def __str__(self):
        return '{} - {}'.format(self.owner.first_name, self.post.title)


class Hidden(models.Model):
    owner =  models.ForeignKey(Customer)
    post = models.ForeignKey(Post, related_name='post')

    def __str__(self):
        return '{} - {}'.format(self.owner.first_name, self.post.title)


class Perk(models.Model):
    title = models.CharField(max_length=200)
    campaign = models.ForeignKey("Campaign")
    price = models.IntegerField()
    retail = models.IntegerField(default=0)
    description = models.TextField()
    num_avail = models.IntegerField(default=1000000)
    num_claimed = models.IntegerField(default=0)
    image = models.ImageField(upload_to="perks", blank=True, null=True)

    def __str__(self):
        return '{} - {}'.format(self.campaign.title, self.title)


class PerkClaim(models.Model):
    campaign = models.ForeignKey("Campaign", related_name="claims")
    # null for donate
    perk = models.ForeignKey(Perk, blank=True, null=True, related_name="claims")
    contact = models.TextField(blank=True, null=True)
    # null for Anonymous
    claimer = models.ForeignKey(Customer, blank=True, null=True)
    amount = models.IntegerField()      # in cent
    transaction = models.CharField(max_length=100)

    def __str__(self):
        return self.campaign.title


class CampCategory(models.Model):
    parent = models.ForeignKey("CampCategory", blank=True, null=True)
    name = models.CharField(max_length=50)
    column = models.IntegerField(default=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Campaign Category'
        verbose_name_plural = 'Campaign Categories'


STAGES = [
    ('concept', 'CONCEPT'),
    ('prototype', 'PROTOTYPE'),
    ('production', 'PRODUCTION'),
    ('shipping', 'SHIPPING')
]

class Campaign(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(CampCategory)
    budget = models.IntegerField()
    raised = models.IntegerField(default=0)
    over_image = models.CharField(max_length=200)
    overview = models.TextField()
    content = models.TextField()
    stage = models.CharField(max_length=200, choices=STAGES)
    duration = models.IntegerField()
    tagline = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    # youtube video keys
    videos = models.TextField(blank=True, null=True)
    owner =  models.ForeignKey(Customer)
    created_at = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.title

templates/post/AptPost.html
{% load extra %}
<div class="row">
    <div class="col-md-3">
        <div class="form-group edit-profile">
            <label>ft<sup>2</sup></label>
            <input type="number" name="area" class="form-control edit-post-wrap" required value="{{ post.area }}" min="0" />
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group edit-profile">
            <label>Available On</label>
            <input type="text" name="available_on" class="form-control edit-post-wrap cl_datepicker" required value="{{ post.available_on|date:'m/d/Y' }}" />
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group edit-profile">
            <label>Bedrooms</label>
            <select name="bedrooms" class="form-control edit-post-wrap" required>
                <option value="">-</option>
                {% for ii in 0|rangee:9 %}
                    <option value="{{ ii }}" {% if post.bedrooms == ii %} selected="" {% endif %}>{{ ii }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group edit-profile">
            <label>Bathrooms</label>
            <select name="bathrooms" class="form-control edit-post-wrap" required>
                <option value="">-</option>
                {% for ii in 0|rangee:9 %}
                    <option value="{{ ii }}" {% if post.bathrooms == ii %} selected="" {% endif %}>{{ ii }}</option>
                {% endfor %}
            </select>
        </div>
    </div>    
    <div class="col-md-3">
        <div class="form-group edit-profile">
            <label>Housing Type</label>
            <select name="type" class="form-control edit-post-wrap" required>
                <option value="">-</option>
                <option value="apartment" {% if post.type == "apartment" %}selected{% endif %}>apartment</option>
                <option value="condo" {% if post.type == "condo" %}selected{% endif %}>condo</option>
                <option value="cottage/cabin" {% if post.type == "cottage/cabin" %}selected{% endif %}>cottage/cabin</option>
                <option value="duplex" {% if post.type == "duplex" %}selected{% endif %}>duplex</option>
                <option value="flat" {% if post.type == "flat" %}selected{% endif %}>flat</option>
                <option value="house" {% if post.type == "house" %}selected{% endif %}>house</option>
                <option value="in-law" {% if post.type == "in-law" %}selected{% endif %}>in-law</option>
                <option value="loft" {% if post.type == "loft" %}selected{% endif %}>loft</option>
                <option value="townhouse" {% if post.type == "townhouse" %}selected{% endif %}>townhouse</option>
                <option value="manufactured" {% if post.type == "manufactured" %}selected{% endif %}>manufactured</option>
                <option value="assited living" {% if post.type == "assited living" %}selected{% endif %}>assited living</option>
                <option value="land" {% if post.type == "land" %}selected{% endif %}>land</option>
            </select>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group edit-profile">
            <label>Laundry</label>
            <select name="laundry" class="form-control edit-post-wrap" required>
                <option value="">-</option>
                <option value="w/d in unit" {% if post.laundry == "w/d in unit" %}selected{% endif %}>w/d in unit</option>
                <option value="w/d hookups" {% if post.laundry == "w/d hookups new" %}selected{% endif %}>w/d hookups</option>
                <option value="laundry in bldg" {% if post.laundry == "laundry in bldg" %}selected{% endif %}>laundry in bldg</option>
                <option value="laundry on site" {% if post.laundry == "laundry on site" %}selected{% endif %}>laundry on site</option>
                <option value="no laundry on site" {% if post.laundry == "no laundry on site" %}selected{% endif %}>no laundry on site</option>
            </select>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group edit-profile">
            <label>Parking</label>
            <select name="parking" class="form-control edit-post-wrap" required>
                <option value="">-</option>
                <option value="carport" {% if post.parking == "carport" %}selected{% endif %}>carport</option>
                <option value="attached garage" {% if post.parking == "attached garage" %}selected{% endif %}>attached garage</option>
                <option value="detached garage" {% if post.parking == "detached garage" %}selected{% endif %}>detached garage</option>
                <option value="off-street parking" {% if post.parking == "off-street parking" %}selected{% endif %}>off-street parking</option>
                <option value="street parking" {% if post.parking == "street parking" %}selected{% endif %}>street parking</option>
                <option value="valet parking" {% if post.parking == "valet parking" %}selected{% endif %}>valet parking</option>
                <option value="no parking" {% if post.parking == "no parking" %}selected{% endif %}>no parking</option>
            </select>
        </div>
    </div>
    <div class="col-md-2 col-xs-4">
        <div class="form-group edit-profile">
            <label>Cats Ok</label>
            <input type="checkbox" name="cats_ok" class="edit-post-wrap" style="display: block;" {% if post.cats_ok %} checked="" {% endif %}>
        </div>
    </div>
    <div class="col-md-2 col-xs-4">
        <div class="form-group edit-profile">
            <label>Dogs Ok</label>
            <input type="checkbox" name="dogs_ok" class="edit-post-wrap" style="display: block;" {% if post.dogs_ok %} checked="" {% endif %}>
        </div>
    </div>
    <div class="col-md-2 col-xs-4">
        <div class="form-group edit-profile">
            <label>Furnished</label>
            <input type="checkbox" name="furnished" class="edit-post-wrap" style="display: block;" {% if post.furnished %} checked="" {% endif %}>
        </div>
    </div>
    <div class="col-md-3 col-xs-6">
        <div class="form-group edit-profile">
            <label>No smoking</label>
            <input type="checkbox" name="no_smoking" class="edit-post-wrap" style="display: block;" {% if post.no_smoking %} checked="" {% endif %}>
        </div>
    </div>
    <div class="col-md-4 col-xs-6">
        <div class="form-group edit-profile">
            <label>Wheelchair accessible</label>
            <input type="checkbox" name="wheelchair" class="edit-post-wrap" style="display: block;" {% if post.wheelchair %} checked="" {% endif %}>
        </div>
    </div>
</div>

templates/post/garagepost.html
{% extends "base.html" %}

{% block page_body %}
    <div class="card" style="min-height: 100vh; font-size: 16px;">                       
        <div class="card-body">
            <div class="row"><div class="col-md-12 m-t-20">
                <div class="col-sm-7">
                    <div class="form-group fg-line">
                        <label class="c-green">posting title</label>
                        <input type="text" class="form-control input-mask" name="title" required="" id="id_title" maxlength="100">
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group fg-line">
                        <label>specific location</label>
                        <input type="text" class="form-control input-mask" name="location" required="" id="id_location" maxlength="100">
                    </div>
                </div>                
                <div class="col-sm-2">
                    <div class="form-group fg-line">
                        <label>postal code</label>
                        <input type="text" class="form-control input-mask" name="postal_code" required="" id="id_postal_code" maxlength="100">
                    </div>
                </div>        

                <div class="col-md-12">
                <p class="c-green f-500 m-t-20 m-b-20">posting body</p>
                <div class="form-group">
                    <div class="fg-line">
                        <textarea class="form-control" style="background-color: #f4f4f4;" rows="5" name="content" id="id_content"></textarea>
                    </div>
                </div>
                </div>

                <div class="col-md-12 m-b-20">
                <div class="col-md-12 p-t-15" style="background-color: #f4f4f4;">
                    <div class="form-group col-md-6">
                        <label for="inputEmail3" class="col-sm-4 control-label c-green">event start date</label>
                        <div class="col-sm-8">
                            <div class="fg-line">
                                <input type="email" class="form-control input-sm" id="inputEmail3">
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputEmail31" class="col-sm-4 control-label c-green">event duration</label>
                        <div class="col-sm-8">
                            <div class="fg-line">
                                <input type="email" class="form-control input-sm" id="inputEmail31">
                            </div>
                        </div>
                    </div>
      
                </div>
                </div>
                
                    <input type="hidden" name="category" required="" id="id_category" value="{{ category }}">                        
                    <input type="hidden" name="owner" required="" id="id_owner">

                <div class="col-md-12 m-b-20">
                <div class="col-md-12 p-t-10" style="background-color: #f4f4f4;">
                    <div class="col-md-5">
                        <div class="form-group fg-line">
                            <label class="c-green">email</label>
                            <input type="text" class="form-control input-mask" name="location" required="" id="id_location" maxlength="100">
                        </div>
                        <div>users can also contact me:</div>
                        <div class="col-sm-6 m-b-20 f-12">
                            <div class="form-group checkbox">
                                <label>by phone
                                <input name="by_phone" id="id_by_phone" type="checkbox" class="form-control">
                                <i class="input-helper"></i>
                                </label>
                            </div>
                        </div>        

                        <div class="col-sm-6 m-b-20 f-12">
                            <div class="form-group checkbox">
                                <label>by text
                                <input name="by_text" id="id_by_text" type="checkbox" class="form-control">
                                <i class="input-helper"></i>
                                </label>
                            </div>
                        </div>        
                    </div>

                    <div class="col-md-7">
                        <div class="radio m-b-15">
                            <label>
                                <input type="radio" name="mail_realy" value="">
                                <i class="input-helper"></i>
                                CL mail relay (recommended) 
                            </label>
                        </div>
                        <div class="radio m-b-15">
                            <label>
                                <input type="radio" name="real_email" value="">
                                <i class="input-helper"></i>
                                show my real email address 
                            </label>
                        </div>
                        <div class="radio m-b-15">
                            <label>
                                <input type="radio" name="no_reply" value="">
                                <i class="input-helper"></i>
                                no replies to this email 
                            </label>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group fg-line">
                                <label>phone number</label>
                                <input type="text" class="form-control input-mask" name="phone" required="" id="id_title" maxlength="100">
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group fg-line">
                                <label>extension</label>
                                <input type="text" class="form-control input-mask" name="extension" required="" id="id_title" maxlength="100">
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group fg-line">
                                <label>contact name</label>
                                <input type="text" class="form-control input-mask" name="name" required="" id="id_title" maxlength="100">
                            </div>
                        </div>

                    </div>
                </div>
                <input type="button" value="continue" class="pull-right m-t-15">
                </div>
            </div></div>
    </div></div>
{% endblock %}

templates/post/pure.html
{% extends "base.html" %}

{% block page_body %}
    <div class="card" style="min-height: 100vh; font-size: 16px;">                       
        <div class="card-body">
            <div class="row"><div class="col-md-12 m-t-20">
                <div class="col-sm-7">
                    <div class="form-group fg-line">
                        <label class="c-green">posting title</label>
                        <input type="text" class="form-control input-mask" name="title" required="" id="id_title" maxlength="100">
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group fg-line">
                        <label>specific location</label>
                        <input type="text" class="form-control input-mask" name="location" required="" id="id_location" maxlength="100">
                    </div>
                </div>                
                <div class="col-sm-2">
                    <div class="form-group fg-line">
                        <label>postal code</label>
                        <input type="text" class="form-control input-mask" name="postal_code" required="" id="id_postal_code" maxlength="100">
                    </div>
                </div>        

                <div class="col-md-12">
                <p class="c-green f-500 m-t-20 m-b-20">posting body</p>
                <div class="form-group">
                    <div class="fg-line">
                        <textarea class="form-control" style="background-color: #f4f4f4;" rows="5" name="content" id="id_content"></textarea>
                    </div>
                </div>
                </div>

                    <input type="hidden" name="category" required="" id="id_category" value="{{ category }}">                        
                    <input type="hidden" name="owner" required="" id="id_owner">

                <div class="col-md-12 m-b-20">
                <div class="col-md-12" style="background-color: #f4f4f4;">
                    <div class="col-md-5">
                        <div class="form-group fg-line">
                            <label class="c-green">email</label>
                            <input type="text" class="form-control input-mask" name="location" required="" id="id_location" maxlength="100">
                        </div>
                        <div>users can also contact me:</div>
                        <div class="col-sm-6 m-b-20 f-12">
                            <div class="form-group checkbox">
                                <label>by phone
                                <input name="by_phone" id="id_by_phone" type="checkbox" class="form-control">
                                <i class="input-helper"></i>
                                </label>
                            </div>
                        </div>        

                        <div class="col-sm-6 m-b-20 f-12">
                            <div class="form-group checkbox">
                                <label>by text
                                <input name="by_text" id="id_by_text" type="checkbox" class="form-control">
                                <i class="input-helper"></i>
                                </label>
                            </div>
                        </div>        
                    </div>

                    <div class="col-md-7">
                        <div class="radio m-b-15">
                            <label>
                                <input type="radio" name="mail_relay" value="">
                                <i class="input-helper"></i>
                                CL mail relay (recommended) 
                            </label>
                        </div>
                        <div class="radio m-b-15">
                            <label>
                                <input type="radio" name="mail_relay" value="">
                                <i class="input-helper"></i>
                                show my real email address 
                            </label>
                        </div>
                        <div class="radio m-b-15">
                            <label>
                                <input type="radio" name="mail_relay" value="">
                                <i class="input-helper"></i>
                                no replies to this email 
                            </label>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group fg-line">
                                <label>phone number</label>
                                <input type="text" class="form-control input-mask" name="phone" required="" id="id_title" maxlength="100">
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group fg-line">
                                <label>extension</label>
                                <input type="text" class="form-control input-mask" name="extension" required="" id="id_title" maxlength="100">
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group fg-line">
                                <label>contact name</label>
                                <input type="text" class="form-control input-mask" name="name" required="" id="id_title" maxlength="100">
                            </div>
                        </div>

                    </div>
                </div>
                <input type="button" value="continue" class="pull-right m-t-15">
                </div>
            </div></div>
    </div></div>
{% endblock %}